# Generated by Django 2.2 on 2019-05-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190425_2038'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demande',
            new_name='Plan',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='demandeTime',
            new_name='createTime',
        ),
    ]
