# Generated by Django 2.2 on 2019-05-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRessource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Plan')),
                ('Ressource', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Ressource')),
            ],
        ),
    ]
