# Generated by Django 2.2 on 2019-05-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Meuble', models.CharField(default='default', max_length=32)),
                ('status', models.CharField(default='bon', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Concerne_Meuble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meuble', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Meuble')),
                ('ressource', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Ressource')),
            ],
        ),
    ]
