# Generated by Django 2.2 on 2019-05-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='demandeDate',
        ),
        migrations.AddField(
            model_name='demande',
            name='demandeTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='nbPerson',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='demande',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demande',
            name='checkout',
            field=models.DateField(),
        ),
    ]
