# Generated by Django 2.2.1 on 2019-05-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='meuble',
        ),
        migrations.CreateModel(
            name='Concerne_Meuble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meuble', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Meuble')),
                ('ressource', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Ressource')),
            ],
        ),
    ]
