# Generated by Django 2.2.1 on 2019-05-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='taille',
        ),
        migrations.AddField(
            model_name='plan',
            name='typeRessource',
            field=models.CharField(default='Standard-Chambre Simple-Non Fumeurs', max_length=150),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='type',
            field=models.CharField(default='Standard-Chambre Simple-Non Fumeurs', max_length=150),
        ),
    ]
