# Generated by Django 2.2.1 on 2019-05-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_planressource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planressource',
            old_name='Plan',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='planressource',
            old_name='Ressource',
            new_name='ressource',
        ),
    ]
