# Generated by Django 2.2 on 2019-05-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190425_2038'),
        ('gestion', '0002_auto_20190526_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Plan')),
            ],
        ),
    ]
