# Generated by Django 2.2 on 2019-05-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_demande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='client',
            new_name='owner',
        ),
    ]
