# Generated by Django 2.2 on 2019-05-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20190526_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='owner',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='client',
            new_name='owner',
        ),
    ]
