# Generated by Django 2.2 on 2019-05-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20190526_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='status',
            field=models.CharField(default='attendu', max_length=20),
        ),
    ]
