# Generated by Django 2.2 on 2019-05-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_demande_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='number',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='plan',
        ),
        migrations.AddField(
            model_name='demande',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='DemandePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Demande')),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Plan')),
            ],
        ),
    ]
