# Generated by Django 2.2 on 2019-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20190527_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
