# Generated by Django 2.2 on 2019-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_plan_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
