# Generated by Django 2.2 on 2019-05-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_demande_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='typeRessource',
            field=models.CharField(default='Standard-Chambre Simple-Non Fumeurs', max_length=150),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='type',
            field=models.CharField(default='Standard-Chambre Simple-Non Fumeurs', max_length=150),
        ),
    ]
