# Generated by Django 2.2 on 2019-05-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20190527_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='taille',
        ),
    ]
