# Generated by Django 2.2 on 2019-04-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='adresse',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='defaut', max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='login',
            field=models.CharField(default='defaut', max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nom',
            field=models.CharField(default='defaut', max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='prenom',
            field=models.CharField(default='defaut', max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='defaut', max_length=20),
        ),
    ]
