# Generated by Django 2.2 on 2019-04-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190424_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeDate', models.DateField(auto_now_add=True)),
                ('checkin', models.DateField(auto_now_add=True)),
                ('checkout', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='attendu', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='Client',
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ressource', models.CharField(default='default', max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(default='default', max_length=32)),
                ('status', models.CharField(default='attendu', max_length=32)),
                ('taille', models.IntegerField(default=0)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Demande')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client'),
        ),
    ]
