# Generated by Django 2.2 on 2019-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190424_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='defaut', max_length=32)),
                ('pwd', models.CharField(default='defaut', max_length=20)),
            ],
        ),
    ]
