# Generated by Django 2.2 on 2019-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_gestionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='demande',
        ),
        migrations.AddField(
            model_name='demande',
            name='demande',
            field=models.ManyToManyField(to='login.Ressource'),
        ),
    ]
