# Generated by Django 2.2 on 2019-04-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190425_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ressource',
            old_name='nom_ressource',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='ressource',
            old_name='price',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='status',
        ),
    ]
