# Generated by Django 2.2 on 2019-04-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190425_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='Ressource',
        ),
    ]
