run:
	python3 manage.py runserver 127.0.0.1:8000

makemi:
	python3 manage.py makemigrations

mi:
	python3 manage.py migrate


clean:
	find client/ -name "*.pyc" |xargs rm -f
	find gestion/ -name "*.pyc" |xargs rm -f
	find login/ -name "*.pyc" |xargs rm -f
	find hotel/ -name "*.pyc" |xargs rm -f
